[project]
name = "test"
version = "0.1.0"
requires_python ">= 3.9"
dependencies = [
    "requests>=2.32.5",
    "responses>=0.26.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.4.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]